---
title: "P8105_hw6_qs2200"
author: "Qi Shao"
date: "11/20/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
```

##Problem 1

Tidy the data.
```{r problem 1.1}
homi_df = read_csv("./data/homicide-data.csv") 
homi_df = 
  homi_df%>%
  mutate(city_state = str_c(city, ", ", state)) %>%
  janitor::clean_names() %>%
  mutate(homi_solved= ifelse(disposition == "Closed by arrest", 1, 0)) %>%
  filter(!(city_state %in%c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>%
  mutate(victim_race = ifelse(victim_race == "White", "white", "non-white"), victim_age = as.integer(victim_age), victim_race = fct_relevel(victim_race, "white", "non-white")) 
```

```{r problem 1.2}
balti_model = homi_df %>%
  filter(city_state == "Baltimore, MD")

glm( homi_solved ~ victim_age + victim_sex + victim_race, data = balti_model, family = binomial()) %>%
broom::tidy() %>%
mutate(OR_estimate = exp(estimate), OR_conf_low = exp(estimate-qnorm(.975)*std.error), OR_conf_high = exp(estimate+qnorm(.975)*std.error)) %>%
filter(term == "victim_racenon-white") %>%
select(term,OR_conf_low, OR_estimate, OR_conf_high) %>% 
knitr::kable(digits = 3)
```

The result of linear model shows that the adjusted odds ratio of solved homicides in which the victim is non-white estimated to be 0.441 times the odds ratio of homicides in which the victim is white.

```{r problem 1.3}

each_city = homi_df %>%
  group_by(city_state) %>%
  nest()

odds_glm = function(df){
  glm( homi_solved ~ victim_age + victim_sex + victim_race, data = df, family =     binomial())  %>%
  broom::tidy() %>%
  mutate(OR_estimate = exp(estimate), OR_conf_low =        exp(estimate-qnorm(.975)*std.error), OR_conf_high = exp(estimate+qnorm(.975)*std.error)) %>%
  filter(term == "victim_racenon-white") %>%
  select(term,OR_conf_low, OR_estimate, OR_conf_high)
}

all_estimate = 
  mutate(each_city, or = map(data, odds_glm)) %>%
  select(city_state, or) %>%
  unnest() %>%
  select(-term)



```
